language: python

python:
  - 2.6
  - 2.7

install:
  - pip install coveralls coverage
  - python setup.py --version
  - pip install -e.

script:
  - coverage run --branch --source spinneret $(type -p trial) spinneret
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
