language: python

python:
  - 2.7
  - pypy

install:
  - pip install coveralls coverage
  - python setup.py --version
  - pip install -e.

script:
  - coverage run --branch --source txspinneret $(type -p trial) txspinneret
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
